apiVersion: nais.io/v1
kind: Alert
metadata:
  name: security-champion-slackbot
  namespace: security-champion-admin
  labels:
    team: security-champion-admin
spec:
  receivers:
    slack:
      channel: '#security-champion-admin'
      send_resolved: false
  alerts:
    - alert: Naisjob failed
      description: Naisjob security-champion-slackbot failed
      expr: kube_job_failed{job_name=~"^security-champion-slackbot.*", namespace="security-champion-admin"} > 0
      for: 1m
      action: "Sjekk loggene"
      severity: warning
